FROM public.ecr.aws/lambda/python:3.13

COPY src/y2026/youtube_agent_2/backend/services/youtube/requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt --target "${LAMBDA_TASK_ROOT}"
COPY src "${LAMBDA_TASK_ROOT}/src"

CMD ["src.y2026.youtube_agent_2.backend.services.youtube.app.lambda_handler.handler"]
